### PR TITLE
Initial hw1 for Mikihisa Yuasa (myuasa2)

### PR DESCRIPTION
**Pull request by miki-yuasa**

### CODE REVIEW

**Comment by Krith22** [comment]
I will review your code..!!

**Comment by Krith22** [comment]
Your code looks really neat and pretty clear as well.

**Comment by Krith22** [comment]
Just a quick word, in TD(0) I also did the same thing, took np.argmax(Q) to get the policy pi, I am pretty sure it's right, but I heard from an another person they used epsilon greedy, so you might wanna cross check.

**Comment by miki-yuasa** [comment]
Thank you for your comment! As far as I searched, TD(0) does not require epsilon to calculate the policy.

**Pull request merged**
